export const posts = {
  latest: [
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryOne: [
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Farnworth News",
      categoryslug: "farnworth",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Farnworth News",
      categoryslug: "farnworth",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Farnworth News",
      categoryslug: "farnworth",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Farnworth News",
      categoryslug: "farnworth",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Farnworth News",
      categoryslug: "farnworth",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryTwo: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-2",
      description: "This is a short description for dummy news 2",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Town Centre News",
      categoryslug: "bolton-town-centre",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryThree: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "People of Bolton",
      categoryslug: "people-of-bolton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryFour: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-2",
      description: "This is a short description for dummy news 2",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title: "Tenetur amet nemo t",
      slug: "est-quibusdam-in-ali",
      description: "Quas sint est ut in",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 06:43:00",
      categoryname: "Bolton Council News",
      categoryslug: "bolton-council",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryFive: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Politics News",
      categoryslug: "politics",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categorySix: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-2",
      description: "This is a short description for dummy news 2",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Crime News",
      categoryslug: "crime",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categorySeven: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-2",
      description: "This is a short description for dummy news 2",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title: "Tenetur amet nemo t",
      slug: "est-quibusdam-in-ali",
      description: "Quas sint est ut in",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 06:43:00",
      categoryname: "Bolton Sports News",
      categoryslug: "sports",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryEight: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-3",
      description: "This is a short description for dummy news 3",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-2",
      description: "This is a short description for dummy news 2",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title: "Tenetur amet nemo t",
      slug: "est-quibusdam-in-ali",
      description: "Quas sint est ut in",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 06:43:00",
      categoryname: "Bolton Events News",
      categoryslug: "events",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryNine: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Astley Bridge News",
      categoryslug: "astley-bridge",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryTen: [
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Westhoughton News",
      categoryslug: "westhoughton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Westhoughton News",
      categoryslug: "westhoughton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Westhoughton News",
      categoryslug: "westhoughton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Westhoughton News",
      categoryslug: "westhoughton",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
  categoryEleven: [
    {
      title: "Dummy News Title 1",
      slug: "dummy-news-title-1",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-10",
      description:
        "Sen. Alex Padilla forcibly removed from DHS event; White House blames him amid political uproar. \n",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event1",
      slug: "dummy-news-title-9",
      description: "This is a short description for dummy news 9",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event2",
      slug: "dummy-news-title-8",
      description: "This is a short description for dummy news 8",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event3",
      slug: "dummy-news-title-7",
      description: "This is a short description for dummy news 7",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-6",
      description: "This is a short description for dummy news 6",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-5",
      description: "This is a short description for dummy news 5",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
    {
      title:
        "White House Blames Sen. Padilla After Forceful Removal from DHS Event",
      slug: "dummy-news-title-4",
      description: "This is a short description for dummy news 4",
      authorname: "Mirza Mueen",
      authorslug: "mirza-mueen",
      authorid: 1,
      publishdate: "2025-06-13 12:16:00",
      categoryname: "Horwich News",
      categoryslug: "horwich",
      image: "https://boltontoday.co.uk/files/People-of-bolton.jpeg",
      imagetitle: "People of Bolton",
      imageslug: "People-of-bolton",
      imagecaption: null,
    },
  ],
};
